# Generated by Django 4.2.7 on 2025-04-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
